// src/types/letele-playing-cards.d.ts
declare module '@letele/playing-cards' {
    import * as React from 'react'

    type CardComponent = React.FC<React.SVGProps<SVGSVGElement>>

    export const B1: CardComponent
    export const B2: CardComponent
    export const C2: CardComponent
    export const C3: CardComponent
    export const C4: CardComponent
    export const C5: CardComponent
    export const C6: CardComponent
    export const C7: CardComponent
    export const C8: CardComponent
    export const C9: CardComponent
    export const C10: CardComponent
    export const Ca: CardComponent
    export const Cj: CardComponent
    export const Cq: CardComponent
    export const Ck: CardComponent
    export const D2: CardComponent
    export const D3: CardComponent
    export const D4: CardComponent
    export const D5: CardComponent
    export const D6: CardComponent
    export const D7: CardComponent
    export const D8: CardComponent
    export const D9: CardComponent
    export const D10: CardComponent
    export const Da: CardComponent
    export const Dj: CardComponent
    export const Dq: CardComponent
    export const Dk: CardComponent
    export const H2: CardComponent
    export const H3: CardComponent
    export const H4: CardComponent
    export const H5: CardComponent
    export const H6: CardComponent
    export const H7: CardComponent
    export const H8: CardComponent
    export const H9: CardComponent
    export const H10: CardComponent
    export const Ha: CardComponent
    export const Hj: CardComponent
    export const Hq: CardComponent
    export const Hk: CardComponent
    export const J1: CardComponent
    export const J2: CardComponent
    export const S2: CardComponent
    export const S3: CardComponent
    export const S4: CardComponent
    export const S5: CardComponent
    export const S6: CardComponent
    export const S7: CardComponent
    export const S8: CardComponent
    export const S9: CardComponent
    export const S10: CardComponent
    export const Sa: CardComponent
    export const Sj: CardComponent
    export const Sq: CardComponent
    export const Sk: CardComponent
}
